spring:
  datasource:
    #   TODO("сделать правильную ссылку для посдреса")
    url: jdbc:h2:file:~/npa
    username: develop
    password: 123456
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true