spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tlh
    username: develop
    password: 123456
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop
